import { useEffect, useState } from 'react';
import { Button, Input, Label, Table, TableBody, TableCell, TableHeader, TableHeaderCell, TableRow } from '@fluentui/react-components';
import { policeApi, configured, supabase } from '../api';
import { LoginPage } from '../pages/LoginPage';
import { EmptyState, OperationsMap, PageHead, StatusBadge } from '../components/Shared';
import { PageLoader } from '../components/PageLoader';
import { OfficersPage } from './OfficersPage';
import { StationsPage } from './StationsPage';
import { RouteMultiSelect } from './RouteMultiSelect';

function CheckpointCreate({ session, routes, stations, onCreated }) {
  const [open, setOpen] = useState(false); const [form, setForm] = useState({ checkpoint_id: '', name: '', lat: '', lng: '', route_ids: [], station_id: '' }); const [error, setError] = useState('');
  const set = (key, value) => setForm(current => ({ ...current, [key]: value }));
  async function create() { try { setError(''); await policeApi('/checkpoints', session, { method: 'POST', body: JSON.stringify({ checkpoint_id: form.checkpoint_id, name: form.name, station_id: form.station_id || null, location: `POINT(${form.lng} ${form.lat})`, route_ids: form.route_ids }) }); setOpen(false); setForm({ checkpoint_id: '', name: '', lat: '', lng: '', route_ids: [], station_id: '' }); onCreated(); } catch (requestError) { setError(requestError.message); } }
  if (!open) return <Button appearance="primary" onClick={() => setOpen(true)}>Create checkpoint</Button>;
  return <section className="police-create surface"><div className="section-heading"><strong>New checkpoint</strong><Button appearance="subtle" onClick={() => setOpen(false)}>Cancel</Button></div><div className="settings-grid"><Label>Checkpoint ID<Input value={form.checkpoint_id} onChange={(_, data) => set('checkpoint_id', data.value)} /></Label><Label>Name<Input value={form.name} onChange={(_, data) => set('name', data.value)} /></Label><Label>Police station<select value={form.station_id} onChange={event => set('station_id', event.target.value)}><option value="">Nearest-station fallback</option>{stations.map(station => <option key={station.station_id} value={station.station_id}>{station.name}</option>)}</select></Label><Label>Latitude<Input value={form.lat} onChange={(_, data) => set('lat', data.value)} /></Label><Label>Longitude<Input value={form.lng} onChange={(_, data) => set('lng', data.value)} /></Label><Label className="wide">Route coverage<RouteMultiSelect routes={routes} value={form.route_ids} onChange={value => set('route_ids', value)} /></Label><div className="wide"><Button appearance="primary" disabled={!form.checkpoint_id || !form.name || !form.lat || !form.lng || !form.route_ids.length} onClick={create}>Create checkpoint</Button>{error && <p className="form-error">{error}</p>}</div></div></section>;
}
export function PoliceApp() {
  const [session, setSession] = useState(null); const [me, setMe] = useState(null); const [data, setData] = useState({ cases: [], routes: [], checkpoints: [], stations: [], overview: {} }); const [page, setPage] = useState('Queue'); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async current => { if (!current) return; try { setLoading(true); const [me, overview, cases, routes, checkpoints, stations] = await Promise.all([policeApi('/me', current), policeApi('/overview', current), policeApi('/cases', current), policeApi('/routes', current), policeApi('/checkpoints', current), policeApi('/stations', current)]); setMe(me); setData({ overview, cases, routes, checkpoints, stations }); setError(''); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  useEffect(() => { if (!configured) { setLoading(false); return; } supabase.auth.getSession().then(({ data }) => { setSession(data.session); load(data.session); }); const { data: listener } = supabase.auth.onAuthStateChange((_, next) => { setSession(next); if (next) load(next); }); return () => listener.subscription.unsubscribe(); }, []);
  if (!session) return <LoginPage onSession={setSession}/>; if (loading) return <PageLoader label="Loading police operations"/>; if (error) return <main className="login"><p>{error}</p><Button onClick={() => supabase.auth.signOut()}>Sign out</Button></main>;
  return <main className="police-shell"><header className="police-top"><div><p className="eyebrow">SAFE RIDE / POLICE</p><strong>Dispatch workspace</strong></div><div><span>{me?.name}</span><Button appearance="subtle" onClick={() => supabase.auth.signOut()}>Sign out</Button></div></header><nav className="police-nav">{['Queue', 'Map', 'Checkpoints', 'Stations', 'Officers'].map(item => <Button key={item} appearance={page === item ? 'primary' : 'subtle'} onClick={() => setPage(item)}>{item === 'Queue' ? 'Active queue' : item === 'Map' ? 'Operations map' : item === 'Checkpoints' ? 'Checkpoint readiness' : item === 'Stations' ? 'Stations & coverage' : 'Officers & assignments'}</Button>)}</nav><section className="police-content">{page === 'Queue' && <><PageHead eyebrow="LIVE CASES" title="Dispatch queue"/><section className="metrics police-metrics"><Metric label="Active cases" value={data.overview.activeCases}/><Metric label="Awaiting acknowledgement" value={data.overview.awaitingAcknowledgement}/><Metric label="Officers on route" value={data.overview.officersOnRoute}/><Metric label="High priority" value={data.overview.highPriority}/></section><Cases rows={data.cases}/></>}{page === 'Map' && <><PageHead eyebrow="INTERNAL MAP" title="Live operations"/><OperationsMap reports={data.cases} routes={data.routes} checkpoints={data.checkpoints}/></>}{page === 'Checkpoints' && <><PageHead eyebrow="READINESS" title="Active checkpoints"><CheckpointCreate session={session} routes={data.routes} stations={data.stations} onCreated={() => load(session)}/></PageHead><Checkpoints rows={data.checkpoints} stations={data.stations}/></>}{page === 'Stations' && <StationsPage session={session} stations={data.stations} reload={() => load(session)}/>} {page === 'Officers' && <OfficersPage session={session} checkpoints={data.checkpoints} reload={() => load(session)}/>}</section></main>;
}
function Metric({ label, value }) { return <article className="metric"><span>{label}</span><strong>{value || 0}</strong><small>Current operational view</small></article>; }
function Cases({ rows }) { return <section className="surface"><Table><TableHeader><TableRow>{['Case', 'Route', 'Vehicle', 'Target', 'Status'].map(item => <TableHeaderCell key={item}>{item}</TableHeaderCell>)}</TableRow></TableHeader><TableBody>{rows.map(row => <TableRow key={row.case_id}><TableCell className="mono">{row.case_id}</TableCell><TableCell>{row.route_name}</TableCell><TableCell>{row.plate_number || row.vehicle_description}</TableCell><TableCell>{row.dispatch_target_name}</TableCell><TableCell><StatusBadge value={row.status}/></TableCell></TableRow>)}</TableBody></Table>{!rows.length && <EmptyState text="No active cases."/>}</section>; }
function Checkpoints({ rows, stations }) { const names = new Map(stations.map(station => [station.station_id, station.name])); return <section className="surface"><Table><TableHeader><TableRow>{['Checkpoint', 'Station', 'Coverage', 'On duty'].map(item => <TableHeaderCell key={item}>{item}</TableHeaderCell>)}</TableRow></TableHeader><TableBody>{rows.map(row => <TableRow key={row.checkpoint_id}><TableCell><strong>{row.name}</strong><small className="mono">{row.checkpoint_id}</small></TableCell><TableCell>{names.get(row.station_id) || 'Nearest-station fallback'}</TableCell><TableCell>{row.route_ids?.join(', ')}</TableCell><TableCell>{row.on_duty_count}</TableCell></TableRow>)}</TableBody></Table>{!rows.length && <EmptyState text="No checkpoints configured."/>}</section>; }
