import { useState } from 'react';
import { Button, Input, Label, Table, TableBody, TableCell, TableHeader, TableHeaderCell, TableRow } from '@fluentui/react-components';
import { SearchRegular } from '@fluentui/react-icons';
import { api } from '../api';
import { PageHead, StatusBadge } from '../components/Shared';

const blank = { checkpoint_id: '', name: '', location: '', route_ids: '', directions_covered: 'eastbound,westbound', shift_start: '06:00', shift_end: '18:00', reason: '' };
export function CheckpointsPage({ rows, session, reload, onSelect }) {
  const [error, setError] = useState(''); const [creating, setCreating] = useState(false); const [form, setForm] = useState(blank);
  const set = (key, value) => setForm(current => ({ ...current, [key]: value }));
  async function setOfficerDuty(checkpoint, officer) { try { await api(`/checkpoints/${checkpoint.checkpoint_id}/officers/${officer.badgeId}/duty-status`, session, { method: 'PATCH', body: JSON.stringify({ onDuty: !officer.onDuty }) }); reload(); } catch (err) { setError(err.message); } }
  async function create() { try { await api('/checkpoints', session, { method: 'POST', body: JSON.stringify({ ...form, route_ids: form.route_ids.split(',').map(x => x.trim()).filter(Boolean), directions_covered: form.directions_covered.split(',').map(x => x.trim()).filter(Boolean), duty_officers: [] }) }); setForm(blank); setCreating(false); reload(); } catch (err) { setError(err.message); } }
  return <><PageHead eyebrow="LIVE DISPATCH CONFIGURATION" title="Checkpoints & roster"><Button appearance="primary" onClick={() => setCreating(value => !value)}>{creating ? 'Cancel' : 'Add checkpoint'}</Button></PageHead>{creating && <section className="settings-grid surface"><Label>Checkpoint ID<Input value={form.checkpoint_id} onChange={(_, d) => set('checkpoint_id', d.value)} /></Label><Label>Name<Input value={form.name} onChange={(_, d) => set('name', d.value)} /></Label><Label>Location WKT<Input placeholder="POINT(longitude latitude)" value={form.location} onChange={(_, d) => set('location', d.value)} /></Label><Label>Route IDs<Input value={form.route_ids} onChange={(_, d) => set('route_ids', d.value)} /></Label><Label>Directions<Input value={form.directions_covered} onChange={(_, d) => set('directions_covered', d.value)} /></Label><Label>Shift start<Input value={form.shift_start} onChange={(_, d) => set('shift_start', d.value)} /></Label><Label>Shift end<Input value={form.shift_end} onChange={(_, d) => set('shift_end', d.value)} /></Label><div><Button appearance="primary" disabled={!form.checkpoint_id || !form.name || !form.location || !form.route_ids} onClick={create}>Create checkpoint</Button></div></section>}<section className="surface"><div className="toolbar"><Input contentBefore={<SearchRegular/>} placeholder="Search checkpoint or corridor"/><span className="toolbar-note">Changes are audited and effective immediately.</span></div>{error && <div className="form-error">{error}</div>}<Table><TableHeader><TableRow>{['Checkpoint','Route coverage','Direction','Duty officers','Shift','Status'].map(item => <TableHeaderCell key={item}>{item}</TableHeaderCell>)}</TableRow></TableHeader><TableBody>{rows.map(row => <TableRow key={row.checkpoint_id}><TableCell><Button appearance="transparent" size="small" onClick={() => onSelect?.(row.checkpoint_id)}>{row.name}</Button></TableCell><TableCell>{(row.route_ids || []).join(', ')}</TableCell><TableCell>{(row.directions_covered || []).join(' / ')}</TableCell><TableCell>{(row.duty_officers || []).map(officer => <button className={`duty-toggle ${officer.onDuty ? 'on' : ''}`} key={officer.badgeId} onClick={() => setOfficerDuty(row, officer)}>{officer.name}: {officer.onDuty ? 'On duty' : 'Off duty'}</button>)}</TableCell><TableCell>{row.shift_start}-{row.shift_end}</TableCell><TableCell><StatusBadge value={row.is_active ? 'Active' : 'Inactive'}/></TableCell></TableRow>)}</TableBody></Table></section></>;
}
