import { Button, Dialog, DialogActions, DialogBody, DialogContent, DialogSurface, DialogTitle, Field, Select, Textarea } from '@fluentui/react-components';
import { useEffect, useState } from 'react';
import { api } from '../api';
import { StatusBadge } from './Shared';

const value = item => item == null || item === '' ? 'Not recorded' : Array.isArray(item) ? item.join(', ') : String(item);
export function RecordDetailDialog({ resource, id, session, onDismiss, reload }) {
  const [record, setRecord] = useState(null); const [error, setError] = useState(''); const [status, setStatus] = useState(''); const [reason, setReason] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!id) return; setRecord(null); setError(''); api(`/${resource}/${encodeURIComponent(id)}`, session).then(setRecord).catch(e => setError(e.message)); }, [resource, id, session]);
  const report = resource === 'reports' ? record : null; const entity = record?.checkpoint || record?.route || record?.user || record; const history = record?.history || [];
  const saveStatus = async () => { try { setSaving(true); await api(`/reports/${encodeURIComponent(id)}/status`, session, { method: 'PATCH', body: JSON.stringify({ status, reason }) }); reload(); onDismiss(); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  return <Dialog open={Boolean(id)} onOpenChange={(_, d) => !d.open && onDismiss()}><DialogSurface><DialogBody><DialogTitle>{resource === 'reports' ? `Case ${id}` : value(entity?.name || entity?.plate_number || entity?.email || id)}</DialogTitle><DialogContent>{error && <p className="form-error">{error}</p>}{!record && !error && <p>Loading record…</p>}{report && <section className="detail-grid"><Detail label="Status"><StatusBadge value={report.status}/></Detail><Detail label="Reported">{new Date(report.reported_at).toLocaleString()}</Detail><Detail label="Route">{value(report.route_name)} {report.direction_of_travel ? `(${report.direction_of_travel})` : ''}</Detail><Detail label="Vehicle">{value(report.plate_number || report.vehicle_description)}</Detail><Detail label="Violation">{value(report.violation_type)}</Detail><Detail label="Dispatch target">{value(report.dispatch_target_name)}</Detail><Detail label="Priority">{value(report.dispatch_priority)}</Detail><Detail label="Prediction">{value(report.prediction_confidence)}</Detail><Detail label="Interception attempts">{report.interception_attempts?.length || 0}</Detail><Field label="Override status"><Select value={status} onChange={(_, d) => setStatus(d.value)}><option value="">Select a status</option>{['Dispatched','Acknowledged','Intercepted','NotSeen','Escalated','Closed','Rejected'].map(item => <option key={item}>{item}</option>)}</Select></Field><Field label="Reason for override"><Textarea value={reason} onChange={(_, d) => setReason(d.value)} /></Field></section>}{entity && !report && <section className="detail-grid">{Object.entries(entity).filter(([key]) => !['location','polyline','duty_officers'].includes(key)).map(([key, item]) => <Detail key={key} label={key.replaceAll('_', ' ')}>{value(item)}</Detail>)}{entity.duty_officers && <Detail label="Duty officers">{entity.duty_officers.map(officer => `${officer.name} (${officer.badgeId}) - ${officer.onDuty ? 'On duty' : 'Off duty'}`).join(', ') || 'None'}</Detail>}</section>}{history.length > 0 && <section className="detail-history"><strong>Change history</strong>{history.map(item => <p key={item.id}>{new Date(item.created_at).toLocaleString()} - {item.action}{item.reason ? `: ${item.reason}` : ''}</p>)}</section>}</DialogContent><DialogActions>{report && <Button appearance="primary" disabled={!status || !reason.trim() || saving} onClick={saveStatus}>{saving ? 'Saving…' : 'Save status'}</Button>}<Button appearance="secondary" onClick={onDismiss}>Close</Button></DialogActions></DialogBody></DialogSurface></Dialog>;
}
function Detail({ label, children }) { return <div><small>{label}</small><div>{children}</div></div>; }
